# Generated by Django 3.0.2 on 2020-04-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_function',
            field=models.CharField(choices=[('EnD', 'Engineering / Design'), ('SPL', 'Supply Chain / Procurement / Logistics'), ('MOp', 'Manufacturing / Operations'), ('Gen', 'General Management'), ('S&M', 'Sales & Marketing'), ('Oth', 'Other')], default='Other', max_length=30),
        ),
    ]
