# Generated by Django 3.0.2 on 2020-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0002_customuser_job_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_function',
            field=models.CharField(choices=[('Engineering / Design', 'Engineering / Design'), ('Supply Chain / Procurement / Logistics', 'Supply Chain / Procurement / Logistics'), ('Manufacturing / Operations', 'Manufacturing / Operations'), ('General Management', 'General Management'), ('Sales & Marketing', 'Sales & Marketing'), ('Other', 'Other')], default='Other', max_length=38),
        ),
    ]
