# Generated by Django 3.0.2 on 2020-02-21 04:24

import django.core.validators
from django.db import migrations, models
import synergy.models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0003_clientlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.AddField(
            model_name='product',
            name='_quality',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, validators=[synergy.models.validate_name]),
        ),
    ]
