# Generated by Django 3.0.2 on 2020-04-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0003_auto_20200410_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_function',
            field=models.CharField(choices=[('END', 'Engineering / Design'), ('SPL', 'Supply Chain / Procurement / Logistics'), ('MOP', 'Manufacturing / Operations'), ('GEN', 'General Management'), ('SAM', 'Sales & Marketing'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
