# Generated by Django 3.0.2 on 2020-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0004_auto_20200410_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_function',
            field=models.CharField(choices=[(None, '- Select -'), ('END', 'Engineering / Design'), ('SPL', 'Supply Chain / Procurement / Logistics'), ('MOP', 'Manufacturing / Operations'), ('GEN', 'General Management'), ('SAM', 'Sales & Marketing'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
