# Generated by Django 3.0.2 on 2020-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0005_auto_20200410_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='POSTAL_CODE',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_website',
            field=models.CharField(choices=[(None, '- Select -'), ('CAN', 'Canada'), ('OTH', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(choices=[(None, '- Select -'), ('AERO', 'Aerospace & Defense'), ('OTH', 'Other')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_level',
            field=models.CharField(choices=[(None, '- Select -'), ('EXC', 'Executive'), ('DIR', 'Director'), ('MNG', 'Manager'), ('IND', 'Individual Contributor'), ('OWN', 'Owner')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_function',
            field=models.CharField(choices=[(None, '- Select -'), ('END', 'Engineering / Design'), ('SPL', 'Supply Chain / Procurement / Logistics'), ('MOP', 'Manufacturing / Operations'), ('GEN', 'General Management'), ('SAM', 'Sales & Marketing'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
