# Generated by Django 3.0.2 on 2020-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0007_auto_20200410_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_website',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[(None, '- Select -'), ('CAN', 'Canada'), ('USA', 'United States'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='industry',
            field=models.CharField(choices=[(None, '- Select -'), ('AERO', 'Aerospace & Defense'), ('AGRI', 'Agriculture & Forestry'), ('AUTO', 'Automotive'), ('BUSI', 'Business'), ('CHEM', 'Chemicals'), ('CONS', 'Construction'), ('DIST', 'Distribution, Wholesale, Retail'), ('EDUC', 'Education'), ('ELCE', 'Electrical Equipment'), ('ELCT', 'Electronics'), ('ENGI', 'Engineering & Technical Services'), ('FOOD', 'Food, Beverage, Tobacco'), ('GOVE', 'Government & Military'), ('MACH', 'Machinery'), ('MANU', 'Manufacturing'), ('MEDI', 'Medical & Healthcare'), ('META', 'Metals - Raw, Formed, Fabricated'), ('MINI', 'Mining, Oil & Gas, Quarrying'), ('OTH', 'Other'), ('PAPE', 'Paper, Paper Products, Printing'), ('PLAS', 'Plastics & Rubber'), ('TEXT', 'Textiles, Apparel, Leather'), ('TRAN', 'Transportation & Logistics'), ('UTIL', 'Utilities & Telecommunications')], max_length=4, null=True),
        ),
    ]
