# Generated by Django 3.0.2 on 2020-02-23 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0007_auto_20200223_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_quality',
            field=models.DecimalField(blank=True, db_column='quality', decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
