# Generated by Django 3.0.2 on 2020-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0008_auto_20200417_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='email address'),
        ),
    ]
