# Generated by Django 3.0.2 on 2020-04-17 16:03

from django.db import migrations
import synergy.models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0009_auto_20200417_1156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', synergy.models.UserManager()),
            ],
        ),
    ]
