# Generated by Django 3.0.2 on 2020-03-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0010_auto_20200223_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='_max_budget',
            new_name='max_budget',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='_min_budget',
            new_name='min_budget',
        ),
    ]
