# Generated by Django 3.0.2 on 2020-04-08 15:30

from django.db import migrations, models
import django.db.models.deletion
import synergy.models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0011_auto_20200229_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[synergy.models.validate_name])),
                ('location', models.CharField(choices=[('domestic', 'domestic'), ('international', 'international')], max_length=13, verbose_name='location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[synergy.models.validate_name])),
                ('location', models.CharField(choices=[('domestic', 'domestic'), ('international', 'international')], max_length=13, verbose_name='location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientLogin',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergy.Supplier'),
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergy.Client'),
        ),
    ]
