# Generated by Django 3.0.2 on 2020-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0011_auto_20200417_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_website',
            field=models.URLField(null=True),
        ),
    ]
