# Generated by Django 3.0.2 on 2020-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0012_customuser_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='info_complete',
            field=models.BooleanField(default=False),
        ),
    ]
