# Generated by Django 3.0.2 on 2020-03-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0012_auto_20200229_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergy.Supplier'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergy.Client'),
        ),
    ]
