# Generated by Django 3.0.2 on 2020-05-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0014_auto_20200424_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='info_complete',
            new_name='verified',
        ),
    ]
