# Generated by Django 3.0.2 on 2020-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0015_auto_20200517_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='info_complete',
            field=models.BooleanField(default=False),
        ),
    ]
