# Generated by Django 3.0.2 on 2020-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0016_customuser_info_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
