# Generated by Django 3.0.2 on 2020-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0018_auto_20200517_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'businesses'},
        ),
    ]
